spring:
  main:
    web-application-type: reactive
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_enums_using_to_string: true
    deserialization:
      read_enums_using_to_string: true
      FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY: false

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  info:
    git:
      mode: full

server:
  port: ${port:8080}

logging:
  level:
    reactor: WARN
    #io.rsocket: TRACE
    #io.netty: DEBUG
    #com.planet.staccato.rsocket: DEBUG
    #com.planet: DEBUG
    #org.springframework: DEBUG
    #com.fasterxml: DEBUG
    #com.planet.staccato.es.initializer: DEBUG
    #com.planet.staccato.es.repository: DEBUG
    #io.grpc: DEBUG
    #org.springframework.web.reactive: TRACE
    o.s.b.web.embedded.netty.NettyWebServer: INFO
    #org.springframework.web: DEBUG
    #com.planet.ng.bcis.index.rsocket: DEBUG
    #reactor.ipc: trace
    #io.api: DEBUG
    #org.springframework.web.reactive.function.client: debug
    #org.springframework.boot.actuate.endpoint.web.reactive.WebFluxEndpointHandlerMapping: WARN
    #org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: WARN

staccato:
  version: 0.9.0-RC2
  rsocket:
    enabled: false
  kafka:
    enabled: false
  grpc:
    enabled: false
  include-null-fields: false
  generate-thumbnail-links: false
  es:
    index:
      auto-initialize: true
      aliases:
        # alias key name should be the alias name, value should be the alias providers value
        landsat-8-l1: landsat-8-l1

